version: 2.1
     
orbs:
  kubernetes: circleci/kubernetes@0.11.2
  aws-eks: circleci/aws-eks@1.0.3

jobs:
  Lint:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: Update & install Dependencies
          command: |
            apt-get update
            echo "|||||-----||||||"
            apt-get install tidy -y
            apt-get install wget -y
            wget -O ./hadolint https://github.com/hadolint/hadolint/releases/download/v1.22.1/hadolint-Linux-x86_64
            chmod +x hadolint
            mv hadolint /bin/hadolint
      - run:
          name: Lint HTML
          command: |
            tidy -q -e *.html
      - run:
          name: Hadolint Dockerfile
          command: |
            hadolint -v
            hadolint --ignore DL3006 Dockerfile

  Dockerize:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker Login
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
      - run: 
          name: Build Image 
          command: |
            docker build -t asghostknight/capstone .
      - run: 
          name: Push Image to DockerHub 
          command: |
            docker push asghostknight/capstone
    
  Update_kubeconfig:
    docker:
    - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name:
          command: |
            ./update_kubeconfig.sh
  
  Kubectl_Apply:
    docker:
    - image: amazon/aws-cli
    steps:
      - checkout
      - kubernetes/install-kubectl
      - run:
          name: Start Blue Service 
          command: |
            kubectl apply -f ./Blue.json        
      - run:
          name: Start Green Service 
          command: |       
            kubectl apply -f ./Green.json

workflows:
  default:
    jobs:
      # - Lint
      # - Dockerize:
      #     requires: [Lint]
      # - Update_kubeconfig:
      #     requires: [Dockerize]
      - Kubectl_Apply
          # requires: [Update_kubeconfig]